### PR TITLE
Fix Shebang

### PR DESCRIPTION
**Pull request by livioso**
*Issue #, if available:*
n/a

*Description of changes:*
typo in shebang

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cmckni3** [comment]
Weird, I fixed this in a previous PR

**Comment by Jerry-AWS** [comment]
Thanks for the submission, and good catch! Merging. You should see the change on docs.aws.amazon.com withinin the next 24 hours.

**Comment by Jerry-AWS** [comment]
@cmckni3 Yeah, I thought it had already been fixed too. I think paths got crossed between our internal XML version of this Guide and the Markdown versions here on GitHub. (The Markdown files here are actually an output of our build process, not source files.)

**Comment by cmckni3** [comment]
Interesting. I see that noted in the readme too.

Is there hesitation to have the source files for cdk docs on GitHub? I have noticed the cdk uses CodeBuild in us-east-1 and integrate with GitHub.

**Comment by Jerry-AWS** [comment]
@cmckni3 The source files are in XML (specifically, a customized flavor of Docbook) and support a lot of features that Markdown doesn't. It is very easy to break the XML if you just get in there and start editing things without a good XML authoring tool and/or the ability to build the docs yourself. 

We estimated that such a high bar for contribution would discourage a lot of community activity, so it made more sense to provide the docs in a more readily editable format like Markdown and handle the complexity of the XML format "behind the curtain."

People both inside and outside Amazon are interested in more community engagement with documentation, and are well aware that our current practice of manually converting contributions back from Markdown to XML doesn't scale, so we're investigating ways to make the situation better. AWS has lots of documentation, though, so I can't promise anything specific in any particular timeframe.

Documentation is like sausage: tasty, but you don't want to watch it being made.  :-)

**Comment by cmckni3** [comment]
Wow, fair enough. Reminds me of the painful process of editing Lotus Notes 🤣.

I overcame a similar learning curve with LaTeX. In the case of LaTeX, I used a VS Code plugin and Docker for fast iteration.

**Pull request merged**
