### PR TITLE
fix(environments): Fix environments bash shebang line for bash

### PR DESCRIPTION
**Pull request by cmckni3**
*Description of changes:*

Fixed path to bash for Linux/Mac OS X scripts

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cmckni3** [comment]
See https://docs.aws.amazon.com/cdk/latest/guide/environments.html#w84aac11c13c31b1

**Comment by Jerry-AWS** [comment]
Looks good; I'm merging it, but it will be a bit before it lands on docs.aws.amazon.com.

**Comment by cmckni3** [comment]
Awesome, thanks!

**Comment by Jerry-AWS** [comment]
No, thank _you!_

**Pull request merged**
