### PR TITLE
Improved tagging API

### PR DESCRIPTION
**Pull request by iamhopaul123**
Improved tagging API.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
@iamhopaul123 Thanks for the contribution! Those look like good improvements; I'll look at integrating them.

Just so you know, the AWS CDK Developer Guide is not built from Markdown; rather, the Markdown files are an output of the build process. So it may take a little while before you see your contribution on docs.aws.amazon.com (it's not quite as simple as just merging your PR). I'll leave this open in the meantime.

**Comment by Jerry-AWS** [comment]
This feature has been released, so I'm going to try to get this merged in today.

**Comment by Jerry-AWS** [comment]
Made these changes and they are in production. Closing this PR since the new content will come from the other direction. Thanks again for submitting this!

**Comment by iamhopaul123** [comment]
Thanks!

**Pull request closed without merging**
