### PR TITLE
Updates environments.md Windows example scripts

### PR DESCRIPTION
**Pull request by bravogolfgolf**
*Issue #239*

*Description of changes:*
Removes uses of 'shift' and '%*' from Windows example scripts. Simplifies Windows scripts.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
My intention using `shift` was to allow the other arguments (including command line flags/options and any number of stack names) to be passed through to `cdk deploy`, which this doesn't do.

A quick Google shows there aren't any really good ways to do what `shift` does in the standard Windows shell. One could just pass all the numbered arguments:

```
@echo off
rem cdk-deploy-to.bat
set CDK_DEPLOY_ACCOUNT=%1
set CDK_DEPLOY_REGION=%2
cdk deploy %3 %4 %5 %6 %7 %8 %9
```

But that's going to blow up as soon as someone wants to pass more than 7 arguments.

It's easy in Powershell, though. Something like this (untested):

```
$env:CDK_DEPLOY_ACCOUNT, $args = $args
$env:CDK_DEPLOY_REGION,  $args = $args
cdk deploy $args
```

Maybe I should switch this over?

**Comment by Jerry-AWS** [comment]
Or maybe people should just install Windows Subsystem for Linux, or Cygwin, and use bash... :-)

**Comment by bravogolfgolf** [comment]
For the stated purpose "For example, you might write your stack to support two additional environment variables to let you override the account and region at synthesis time" I think leaving it a simple as possible is best.

**Comment by Jerry-AWS** [comment]
Let me mull this over for a bit. The Powershell + a batch file to run it would only be four lines, and functionally equivalent to the bash, which appeals to me.

**Comment by Jerry-AWS** [comment]
I'm merging this, thanks again! I will probably rework it some more since I think being able to pass options is an important feature, but yours works!

**Comment by bravogolfgolf** [comment]
Hey @Jerry-AWS I was checking the environment page on the website and noticed the changes from this pull request are not reflected there yet. When will other benefit from the change?

**Pull request merged**
