### PR TITLE
Add all options to tools

### PR DESCRIPTION
**Pull request by hacker65536**
*Issue #, if available:*

*Description of changes:*
relevant to #123 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
@hacker65536 Nice PR, and useful content. I'll take a look at integrating this in the next day or so.

**Comment by hacker65536** [comment]
I deleted redundant writings, and fetch a new output from upstream.

https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/bin/cdk.ts

**Comment by Jerry-AWS** [comment]
@hacker65536 Thanks for the update! It's taken longer than I expected to get to this, but I hope to merge this PR within the next few days.

**Comment by Jerry-AWS** [comment]
Merging at last!

**Comment by hacker65536** [comment]
@Jerry-AWS Thank you.

**Pull request merged**
