### PR TITLE
Updating TS imports to modern style

### PR DESCRIPTION
**Pull request by devndive**
With the switch to a mordern style of imports it is a bit harder to
understand where certain classes (e.g. App, Construct, Queue) come from.
To make it a bit easier to follow the code the imports where added to all
code snippets.

Related to awsdocs/aws-cdk-guide#149

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by devndive** [comment]
Hi,

please regard this PR as a form of RFC since I added imports to all code snippets on the two pages.
Since the issue did not have any guidance on how it should be, I took an approach on how I like to have documentation.

Also please note that the signature for the method `S3.Bucket.addObjectCreatedNotification` changed and now expects a `IBucketNotificationDestination` as first parameter.

**Comment by Jerry-AWS** [comment]
@devndive Thanks for the PR! This is very close to what I want to do (including adding the imports to the snippets that don't have them, although I might use comments). Your other changes look good, too. I'll try to get to this soon!

**Comment by devndive** [comment]
@Jerry-AWS Are there any updates on this topic?

**Comment by Jerry-AWS** [comment]
@devndive I'm merging this, finally. Thanks for the contribution! What you'll actually see is a little different from what you submitted, as I decided to minimize the changes needed to the rest of the code for now, and do the rest as part of an effort to improve consistency across all code snippet languages. You should see the first round of changes on docs.aws.amazon.com in the next few days.

**Pull request merged**
